-- MySQL Script generated by MySQL Workbench
-- Thu Feb 15 00:24:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kitchening_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kitchening_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kitchening_db` DEFAULT CHARACTER SET utf8 ;
USE `kitchening_db` ;

-- -----------------------------------------------------
-- Table `kitchening_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening_db`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `province` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening_db`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening_db`.`restaurants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `coverPrice` INT NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `menu_file` VARCHAR(255) NULL,
  `menu_url` VARCHAR(255) NULL,
  `url_map` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `categoryId` INT NULL,
  `addressId` INT NULL,
  `capacity` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_categories_idx` (`categoryId` ASC) VISIBLE,
  INDEX `fk_users_address_idx` (`addressId` ASC) VISIBLE,
  CONSTRAINT `fk_restaurants_categories`
    FOREIGN KEY (`categoryId`)
    REFERENCES `kitchening_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurants_address`
    FOREIGN KEY (`addressId`)
    REFERENCES `kitchening_db`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening_db`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL,
  `avatar` VARCHAR(255) NULL,
  `addressId` INT NULL,
  `roleId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_address_idx` (`addressId` ASC) VISIBLE,
  INDEX `fk_users_roles_idx` (`roleId` ASC) VISIBLE,
  CONSTRAINT `fk_users_address`
    FOREIGN KEY (`addressId`)
    REFERENCES `kitchening_db`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roleId`)
    REFERENCES `kitchening_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening_db`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening_db`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file` VARCHAR(2555) NULL,
  `restaurantId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_restaurants_idx` (`restaurantId` ASC) VISIBLE,
  CONSTRAINT `fk_images_restaurants`
    FOREIGN KEY (`restaurantId`)
    REFERENCES `kitchening_db`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening_db`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening_db`.`bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `restaurantId` INT NULL,
  `date` DATETIME NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bookings_user_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_bookings_restaurants_idx` (`restaurantId` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_user`
    FOREIGN KEY (`userId`)
    REFERENCES `kitchening_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_restaurants`
    FOREIGN KEY (`restaurantId`)
    REFERENCES `kitchening_db`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening_db`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening_db`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `restaurantId` INT NOT NULL,
  `comment` TEXT NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reviews_users_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_reviews_restaurants_idx` (`restaurantId` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_users`
    FOREIGN KEY (`userId`)
    REFERENCES `kitchening_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_restaurants`
    FOREIGN KEY (`restaurantId`)
    REFERENCES `kitchening_db`.`restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening_db`.`methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening_db`.`methods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening_db`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening_db`.`statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kitchening_db`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kitchening_db`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `bookingId` INT NOT NULL,
  `methodId` INT NOT NULL,
  `statusId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payments_bookings_idx` (`bookingId` ASC) VISIBLE,
  INDEX `fk_payments_methods_idx` (`methodId` ASC) VISIBLE,
  INDEX `fk_payments_status_idx` (`statusId` ASC) VISIBLE,
  CONSTRAINT `fk_payments_bookings`
    FOREIGN KEY (`bookingId`)
    REFERENCES `kitchening_db`.`bookings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_methods`
    FOREIGN KEY (`methodId`)
    REFERENCES `kitchening_db`.`methods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_status`
    FOREIGN KEY (`statusId`)
    REFERENCES `kitchening_db`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
